Areas/Admin/Controllers/Api/CompaniesController.cs
using AutoMapper;
using BookBazaar.Entities;
using BookBazaar.Profiles.Dtos;
using BookBazaar.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookBazaar.Areas.Admin.Controllers.Api
{
    [ApiController]
    [Route("api/v{version:apiVersion}/[controller]")]
    [ApiVersion("1.0")]
    [Produces("application/json")]
    public class CompaniesController : ControllerBase
    {
        private readonly IUnitOfWork<Company> _company;
        private readonly IMapper _mapper;

        public CompaniesController(IUnitOfWork<Company> company, IMapper mapper)
        {
            _company = company;
            _mapper = mapper;
        }

        // GET: /api/companies
        [HttpGet]
        [HttpHead]
        public async Task<IActionResult> GetCompanies()
        {
            var companies = await _company.Entity.GetAllAsync();
            return Ok(companies);
        }

        //GET: /api/v1/companies/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetBook(int id)
        {

            var company = await _company.Entity.GetFirstOrDefaultAsync(p => p.Id == id);

            if (company == null)
                return NotFound();

            return Ok(_mapper.Map<Company, CompanyDto>(company));
        }


        // PUT /api/Books/1
        [HttpPut]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> UpsertBook(int id, CompanyDto companyDto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var companyInDb = await _company.Entity.GetFirstOrDefaultAsync(p => p.Id == id);

            if (companyInDb == null)
                return NotFound();

            var _mappedCompany = _mapper.Map(companyDto, companyInDb);

            await _company.Entity.UpdateAsync(_mappedCompany);
            await _company.CompleteAsync();

            return Ok();
        }


        // GET: /api/companies/5
        [HttpDelete("{id}")]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Delete(int? id)
        {
            Company companyInDb = await _company.Entity.GetFirstOrDefaultAsync(c => c.Id == id);

            if (companyInDb == null)
                return NotFound();

            await _company.Entity.DeleteAsync(companyInDb.Id);
            await _company.CompleteAsync();

            return Ok(companyInDb);

        }
    }
}

Areas/Admin/Controllers/CompanyController.cs
using BookBazaar.Entities;
using BookBazaar.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookBazaar.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork<Company> _company;

        public CompanyController(IUnitOfWork<Company> company)
        {
            _company = company;
        }



        // GET: CompanyController
        public async Task<IActionResult> Index()
        {
            IEnumerable<Company> companies = await _company.Entity.GetAllAsync();
            return View(companies);
        }

        // GET: BookController/Upsert/5
        public async Task<IActionResult> Upsert(int? id)
        {
            Company company = new();

            if (id == null || id == 0)
                return View(company);
            else
            {
                company = await _company.Entity.GetFirstOrDefaultAsync(u => u.Id == id);
                return View(company);
            }
        }

        // POST: BookController/Upsert/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Upsert(Company company)
        {
            if (ModelState.IsValid)
            {


                if (company.Id == 0)
                    await _company.Entity.InsertAsync(company);

                else
                {
                    await _company.Entity.UpdateAsync(company);
                }

                await _company.CompleteAsync();
                TempData["Success"] = "Company saved successfully.";

                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }
    }
}

Areas/Admin/Views/Company/Index.cshtml
@{
    ViewData["Title"] = "Index";
#pragma warning disable
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Companies</h2>
        </div>
        <div class="col-6 text-end">
            <a class="btn btn-primary" asp-controller="Company" asp-action="Upsert">
                <i class="bi bi-plus-circle"></i> &nbsp; New
            </a>
        </div>
    </div>
    <br>
    <table id="companies" class="table table-striped table-hover stripe w-100">
        <thead>
            <tr>
                <th scope="col">
                    @Html.DisplayName("Company")
                </th>        
                <th scope="col">
                    @Html.DisplayName("Street Address")
                </th>
                <th scope="col">
                    @Html.DisplayName("City")
                </th>
                <th scope="col">
                    @Html.DisplayName("State")
                </th>
                <th scope="col">
                    @Html.DisplayName("Postal Code")
                </th>
                <th scope="col">
                    @Html.DisplayName("Phone Number")
                </th>
                <th scope="col"></th>
            </tr>
        </thead>
    </table>
</div>

@section scripts
{

<script>
$(document).ready(function () {
    var table = $("#companies").DataTable({
        ajax: {
            url: "/api/v1/companies/",
            type: "GET",
            dataType: "json",
            dataSrc:""
        },
        columns: [
            {
                data: "name",
            },
            {
                data: "streetAddress",
            },
            {
                data: "city",
            },              
            {
                data: "state",
            },
            {
                data: "postalCode",
            },            
            {
                data: "phoneNumber",
            },
            {
                data: "id",
                render: function(data, type, company) {
                    return `<a class='btn-link' href='/Admin/Company/Upsert/${company.id}'><i class='bi bi-pencil-square' style='color:#75caeb; cursor:pointer;'></i></a>
                            <a class='btn-link js-delete' data-company-id=${company.id}><i class='bi bi-trash-fill' style='color: #ff4136; cursor:pointer;'></a>`
                },
                className: 'text-light dt-body-center'
            }
        ]
    });
    $("#companies").on("click", ".js-delete", function () {
        var button = $(this);
        Swal.fire({
            title: `Are you sure you want to delete this company ?`,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#d33',
            cancelButtonColor: '#5ea2bc',
            confirmButtonText: 'Confirm'
        }).then((result) => {
             if (result.isConfirmed) {
                 $.ajax({
                     url: "/api/v1/companies/" + button.attr("data-company-id"),
                     type: 'DELETE',
                     dataType: "json",
                     dataSrc:"",
                     success: function (data) {
                         if (data) {
                             table.ajax.reload();
                             toastr.success("Company deleted successfully.");
                             table.row(button.parents("tr")).remove().draw();
                          }
                     }, 
                     error: function(){
                        toastr.error("Something went wrong!");
                     }
                 })
             }
        }).catch(()=>{
            toastr.error("An unexpected error occurred please try again later !");
        })
   }) 
});
</script>
} 

Areas/Admin/Views/Company/Upsert.cshtml
@model BookBazaar.Entities.Company

@{
	#pragma warning disable
}

<h2 class="text-primary">@(Model.Id !=0? "Update" : "Create") Company</h2>


<div class="row">
	<div class="col-md-8 mr-2">
		<form method="post" asp-action="Upsert" enctype="multipart/form-data">
			<div asp-validation-summary="All" class="text-danger"></div>
			<input asp-for="Id" hidden />
			<div class="form-group mb-3 col-12  ">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group mb-3 col-12  ">
				<label asp-for="StreetAddress" class="control-label"></label>
				<input asp-for="StreetAddress" class="form-control" />
				<span asp-validation-for="StreetAddress" class="text-danger"></span>
			</div>
			<div class="form-group row">
				<div class="form-group mb-3 col-6">
					<label asp-for="City" class="control-label"></label>
					<input asp-for="City" class="form-control" />
					<span asp-validation-for="City" class="text-danger"></span>
				</div>
				<div class="form-group mb-3 col-6">
					<label asp-for="State" class="control-label"></label>
					<input asp-for="State" class="form-control" />
					<span asp-validation-for="State" class="text-danger"></span>
				</div>
				<div class="form-group mb-3 col-6">
					<label asp-for="PostalCode" class="control-label"></label>
					<input asp-for="PostalCode" class="form-control" />
					<span asp-validation-for="PostalCode" class="text-danger"></span>
				</div>
				<div class="form-group mb-3 col-6">
					<label asp-for="PhoneNumber" class="control-label"></label>
					<input asp-for="PhoneNumber" class="form-control" />
					<span asp-validation-for="PhoneNumber" class="text-danger"></span>
				</div>
			</div>
			<div class="form-group mt-3">
				@if (Model.Id != 0)
				{
					<input type="submit" value="Update" class="btn btn-primary" />
				}
				else
				{
					<input type="submit" onclick="return ValideInputWithImage()" value="Create" class="btn btn-primary" />
				}
				<button asp-action="Index" class="btn btn-secondary">Back to list</button>
			</div>
		</form>
	</div>
</div>



@section Scripts {
	@{
	<partial name="_ValidationScriptsPartial" />
	}
}