Areas/Admin/Controllers/AuthorController.cs
using BookBazaar.Entities;
using BookBazaar.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookBazaar.Controllers
{
#pragma warning disable
    [Area("Admin")]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class AuthorController : Controller
    {
        private readonly IUnitOfWork<Author> _author;

        public AuthorController(IUnitOfWork<Author> author)
        {
            _author = author;
        }

        // GET: Author
        public async Task<IActionResult> Index()
        {
            var authors = await _author.Entity.GetAllAsync(filter: null, includeProperties: a => a.Books);
            return View(authors);
        }

        // GET: Author/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Author/Create  
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for   
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.  
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Create([Bind("Id,FullName")] Author author)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var obj = await _author.Entity.GetFirstOrDefaultAsync(c => c.Id == author.Id);
                    if (obj == null)
                    {
                        await _author.Entity.InsertAsync(author);
                        await _author.CompleteAsync();
                        TempData["Success"] = "Author created successfully.";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("Error", "An unexpected error occurred!");
                    }
                }
            }
            catch
            {
                ModelState.AddModelError("Error", "An Expected Error!");
            }

            return View(author);
        }


        // GET: Author/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Author autor = await _author.Entity.GetFirstOrDefaultAsync(a => a.Id == id, includeProperties: "Books");

            if (autor == null)
            {
                return NotFound();
            }
            return View(await Task.FromResult(autor));
        }

        // GET: Author/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var author = await _author.Entity.GetFirstOrDefaultAsync(c => c.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(await Task.FromResult(author));
        }

        // POST: Author/Edit/5  
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for   
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.  
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _author.Entity.UpdateAsync(author);
                    await _author.CompleteAsync();
                    TempData["Success"] = "author upaded successfully.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Author/Delete/5  
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Author author = await _author.Entity.GetFirstOrDefaultAsync(c => c.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(await Task.FromResult(author));
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var author = await _author.Entity.GetByIdAsync(id);
            await _author.Entity.DeleteAsync(author.Id);
            await _author.CompleteAsync();
            TempData["Success"] = "Author deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> AuthorExists(int id)
        {
            return await _author.Entity.ExistsAsync(id);
        }
    }
}

Areas/Admin/Controllers/BookController.cs
using BookBazaar.Entities;
using BookBazaar.ViewModels;
using BookBazaar.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
//using Microsoft.AspNetCore.Mvc.Rendering;
//using SixLabors.ImageSharp;
//using SixLabors.ImageSharp.Processing;

namespace BookBazaar.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class BookController : Controller
    {
        private readonly IUnitOfWork<Book> _Book;
        private readonly IUnitOfWork<Author> _author;
        private readonly IUnitOfWork<Category> _category;
        private readonly IUnitOfWork<Cover> _cover;
        private readonly IWebHostEnvironment _hostEnvironment;

        public BookController(IUnitOfWork<Book> Book, IUnitOfWork<Category> category, IUnitOfWork<Cover> cover, IUnitOfWork<Author> author, IWebHostEnvironment hostEnvironment)
        {
            _Book = Book;
            _category = category;
            _cover = cover;
            _author = author;
            _hostEnvironment = hostEnvironment;
        }

        // GET: BookController
        public async Task<ActionResult> Index()
        {
            IEnumerable<Book> Books = await _Book.Entity.GetAllAsync();
            return View(Books);
        }

        // GET: BookController/Upsert/5
        public async Task<IActionResult> Upsert(int? id)
        {
            IEnumerable<Category> categories = await _category.Entity.GetAllAsync();
            IEnumerable<Cover> covers = await _cover.Entity.GetAllAsync();
            IEnumerable<Author> authors = await _author.Entity.GetAllAsync();

            BookViewModel model = new()
            {
                Book = new(),

                Categories = categories.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                Covers = covers.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                }),
                Authors = authors.Select(i => new SelectListItem
                {
                    Text = i.FullName,
                    Value = i.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                // create Book
                //ViewBag.Categories = model.Categories;
                //ViewData["Covers"] = model.Covers;
                return View(model);
            }
            else
            {
                // update Book
                model.Book = await _Book.Entity.GetFirstOrDefaultAsync(m => m.Id == id);
                return View(model);
            }
        }

        // POST: BookController/Upsert/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Upsert(BookViewModel model, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\Books");
                    var extension = Path.GetExtension(file.FileName).ToLower();

                    if (model.Book.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, model.Book.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }


                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }

                    model.Book.ImageUrl = @"\images\Books\" + fileName + extension;


                    ResizeImage(file, Path.Combine(uploads, fileName + extension));
                }

                if (model.Book.Id == 0)
                {
                    await _Book.Entity.InsertAsync(model.Book);
                }
                else
                {
                    await _Book.Entity.UpdateAsync(model.Book);
                }

                await _Book.CompleteAsync();
                TempData["Success"] = "Book created successfully.";

                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public void ResizeImage(IFormFile file, string path)
        {
            //using var image = Image.Load(file.OpenReadStream());
            //image.Mutate(x => x.Resize(456, 650));
            //image.Save(path);
        }
    }
}

Areas/Admin/Controllers/CoverController.cs
using BookBazaar.Entities;
using BookBazaar.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookBazaar.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, SuperAdmin")]
    public class CoverController : Controller
    {
        private readonly IUnitOfWork<Cover> _cover;

        public CoverController(IUnitOfWork<Cover> cover)
        {
            _cover = cover;
        }

        // GET: CoverController
        public async Task<ActionResult> Index()
        {
            IEnumerable<Cover> covers = await _cover.Entity.GetAllAsync();
            return View(covers);
        }

        // GET: CoverController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CoverController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Create([Bind("Id,Name")] Cover cover)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _cover.Entity.InsertAsync(cover);
                    await _cover.CompleteAsync();
                    TempData["Success"] = "Cover created successfully.";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                ModelState.AddModelError(string.Empty, "An Expected Error!");
            }

            return View();
        }

        // GET: CoverController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var cover = await _cover.Entity.GetFirstOrDefaultAsync(c => c.Id == id);
            if (cover == null)
            {
                return NotFound();
            }

            return View(cover);
        }

        // POST: CoverController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Cover cover)
        {
            if (id != cover.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _cover.Entity.UpdateAsync(cover);
                    await _cover.CompleteAsync();
                    TempData["Success"] = "Category upaded successfully.";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (await CoverExists(cover.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cover);
        }


        // GET: CoverController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cover = await _cover.Entity.GetFirstOrDefaultAsync(c => c.Id == id);
            if (cover == null)
            {
                return NotFound();
            }

            return View(cover);
        }

        // POST: CoverController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var cover = await _cover.Entity.GetByIdAsync(id);
                await _cover.Entity.DeleteAsync(cover.Id);
                await _cover.CompleteAsync();
                TempData["Success"] = "Category deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private async Task<bool> CoverExists(int id)
        {
            return await _cover.Entity.ExistsAsync(id);
        }
    }
}

ViewComponents/ShoppingCartViewComponent.cs
using BookBazaar.Entities;
using BookBazaar.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Books.ViewComponents
{
#pragma warning disable
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork<ShoppingCart> _shoppingCart;
 
        public ShoppingCartViewComponent(IUnitOfWork<ShoppingCart> shoppingCart)
        {
            _shoppingCart = shoppingCart;
         }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ClaimsIdentity identity = (ClaimsIdentity)User.Identity;
            Claim claim = identity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim == null)
                return View(0);

            var carts = await _shoppingCart.Entity.GetAllAsync(c => c.ApplicationUserId == claim.Value, includeProperties: p => p.Book);
             
            var items = 0;
            foreach (var cart in carts)
            {
                items += cart.Count;
            }

            return View(items);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using BookBazaar.Utilities

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookBazaar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookBazaar.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book Bazaar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse row">
                    <ul class="navbar-nav ">
                        @if (User.Identity.IsAuthenticated && (User.IsInRole(Roles.RoleType.Admin.ToString()) || User.IsInRole(Roles.RoleType.SuperAdmin.ToString())))
                        {
                            <li class="nav-item dropdown px-2">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Manager</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Author" asp-action="Index">Authors</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Book" asp-action="Index">Books</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Cover" asp-action="Index">Covers</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Companies</a>
                                </div>
                            </li>
                            <li class="nav-item px-2">
                                <a class="nav-link" asp-controller="Order" asp-action="Index" asp-area="Admin">
                                    Order Manager
                                </a>
                            </li>
                        }
                        else if ((!User.IsInRole(Roles.RoleType.Admin.ToString()) || !User.IsInRole(Roles.RoleType.SuperAdmin.ToString())) && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item px-2">
                                <a class="nav-link" asp-controller="Order" asp-action="Index" asp-area="Admin">
                                    Order Manager
                                </a>
                            </li>
                        }
                        <li class="nav-item px-2 position-relative">
                            <a class="nav-link" asp-controller="Cart" asp-action="Index" asp-area="Customer">
                                <i class="bi bi-cart text-success"></i>Cart
                                @* @await Component.InvokeAsync("ShoppingCart") *@
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookBazaar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>